import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,stepGame,MODES,DIFFICULTIES,JUMP,OBSTACLES,WORLD_LIMIT,circleHitsRect} from '../dist/engine.js';
const still={forward:0,right:0,boost:false,jump:false};
function playing(mode='foot',difficulty='normal'){const g=createGame(mode,difficulty,123);g.status='playing';return g}
function advance(g,seconds,input=still,hz=120){for(let i=0;i<Math.round(seconds*hz);i++)stepGame(g,input,1/hz)}
function noEnemies(g){g.nextDrone=Infinity;return g}
function incoming(g,{id=1,y=.95,z=g.player.z-2,speed=27,phase='commit'}={}){return {id,x:g.player.x,y,z,vx:0,vy:0,vz:speed,age:0,phase,roll:0,closest:Infinity,passed:false}}

test('ready and paused states freeze',()=>{const g=createGame();advance(g,1,{forward:1,jump:true});assert.equal(g.elapsed,0);g.status='paused';advance(g,1);assert.equal(g.player.z,24);assert.equal(g.player.altitude,0)});
test('surviving 45 seconds produces success and freezes state',()=>{const g=noEnemies(playing());advance(g,46);assert.equal(g.status,'won');assert.equal(g.elapsed,45);advance(g,2,{forward:1});assert.equal(g.player.z,24)});
test('reference speed caps use published civilian maxima',()=>{assert.equal(DIFFICULTIES.easy.speed,16);assert.equal(DIFFICULTIES.normal.speed,27);assert.equal(DIFFICULTIES.hard.speed*3.6,140)});
test('standing still is caught; incoming drone never pauses to aim',()=>{const g=playing();const speeds=[];for(let i=0;i<15*120&&g.status==='playing';i++){stepGame(g,still,1/120);for(const d of g.drones){assert.notEqual(d.phase,'aim');speeds.push(Math.hypot(d.vx,d.vy,d.vz))}}assert.equal(g.status,'lost');assert.ok(g.elapsed>4&&g.elapsed<7);assert.ok(Math.min(...speeds)>=27*.82);assert.ok(Math.max(...speeds)<=27+1e-9)});
test('straight sprinting is insufficient in the pressure scenario',()=>{const g=playing();advance(g,10,{forward:1,boost:true});assert.equal(g.status,'lost');assert.ok(g.distance>10)});
test('steering preserves speed and cannot instantaneously reverse',()=>{const g=noEnemies(playing());const d=incoming(g,{phase:'approach',z:24});d.x=35;d.y=4;d.vz=-27;g.drones.push(d);stepGame(g,still,1/120);assert.ok(Math.abs(Math.hypot(d.vx,d.vy,d.vz)-27)<1e-8);assert.ok(d.vz<-26);assert.ok(d.vx<0);assert.ok(Math.abs(d.roll)>0)});
test('committed approach keeps direction and momentum past its target',()=>{const g=noEnemies(playing());const d=incoming(g,{y:4,z:20});g.drones.push(d);advance(g,.4,{right:1});assert.equal(d.phase,'pass');assert.ok(d.z>24);assert.equal(d.vz,27);assert.equal(d.vx,0);assert.equal(d.vy,0)});
test('high-speed 3D collision cannot tunnel through any transport',()=>{for(const mode of Object.keys(MODES)){const g=noEnemies(playing(mode));g.drones.push(incoming(g,{speed:140/3.6}));stepGame(g,still,.2);assert.equal(g.player.health,MODES[mode].health-1,mode)}});
test('armor survives one impact and fails on second; simultaneous hits are gated',()=>{const g=noEnemies(playing('armor'));g.drones.push(incoming(g),incoming(g,{id:2}));advance(g,.2);assert.equal(g.player.health,1);assert.equal(g.damageCount,1);advance(g,2.1);g.drones.push(incoming(g,{id:3}));advance(g,.2);assert.equal(g.status,'lost')});
test('flight above the player does not collide',()=>{const g=noEnemies(playing());g.drones.push(incoming(g,{y:4}));advance(g,.3);assert.equal(g.player.health,1)});
test('jump follows a vertical arc, costs energy, and lands',()=>{const g=noEnemies(playing());stepGame(g,{jump:true},1/120);assert.ok(g.player.energy<100-JUMP.cost+1);let peak=0;for(let i=0;i<120;i++){stepGame(g,{jump:true},1/120);peak=Math.max(peak,g.player.altitude)}assert.ok(peak>.8&&peak<1.1);assert.equal(g.player.altitude,0);assert.equal(g.player.y,MODES.foot.eye);assert.equal(g.player.invulnerable,0)});
test('holding jump does not auto-hop; vehicles cannot jump',()=>{const g=noEnemies(playing());advance(g,3,{jump:true});assert.equal(g.player.altitude,0);stepGame(g,still,1/120);stepGame(g,{jump:true},1/120);assert.ok(g.player.altitude>0);for(const mode of ['bike','armor']){const v=noEnemies(playing(mode));advance(v,1,{jump:true});assert.equal(v.player.altitude,0);assert.equal(v.player.energy,100)}});
test('jump changes the actual hit volume, without granting invulnerability',()=>{const ground=noEnemies(playing()),jumping=noEnemies(playing());advance(jumping,.36,{jump:true});ground.drones.push(incoming(ground,{y:.2}));jumping.drones.push(incoming(jumping,{y:.2}));advance(ground,.15);advance(jumping,.15);assert.equal(ground.status,'lost');assert.equal(jumping.status,'playing');const hitInAir=noEnemies(playing());advance(hitInAir,.25,{jump:true});hitInAir.drones.push(incoming(hitInAir,{y:hitInAir.player.altitude+.85}));advance(hitInAir,.15);assert.equal(hitInAir.status,'lost')});
test('jump plus direction produces a lateral airborne move',()=>{const g=noEnemies(playing());advance(g,.3,{jump:true,right:1});assert.ok(g.player.x>.5);assert.ok(g.player.altitude>.7)});
test('close missed passes trigger a single pass-by event',()=>{const g=noEnemies(playing());const d=incoming(g,{y:1});d.x=1.4;g.drones.push(d);advance(g,.4);assert.equal(g.status,'playing');assert.equal(g.passCount,1);assert.equal(g.nearMisses,1);assert.equal(g.lastPass.side,1);advance(g,.3);assert.equal(g.passCount,1)});
test('foot motion is camera-relative with diagonal normalization',()=>{const a=noEnemies(playing()),b=noEnemies(playing());advance(a,.5,{forward:1});advance(b,.5,{forward:1,right:1});assert.ok(Math.abs(a.player.speed-b.player.speed)<.01);const c=noEnemies(playing());c.player.yaw=Math.PI/2;advance(c,.5,{forward:1});assert.ok(c.player.x<0);assert.ok(Math.abs(c.player.z-24)<.01)});
test('looking in a vehicle does not steer; A/D steers its chassis',()=>{const g=noEnemies(playing('bike'));g.player.yaw=Math.PI/2;advance(g,1,{forward:1});assert.ok(Math.abs(g.player.x)<.01);assert.ok(g.player.z<24);advance(g,.3,{forward:1,right:1});assert.ok(g.player.bodyYaw<0);assert.ok(g.player.x>0)});
test('boost drains energy and release restores it',()=>{const g=noEnemies(playing());advance(g,1,{forward:1,boost:true});assert.ok(g.player.energy<80);assert.ok(g.player.speed>MODES.foot.speed);advance(g,10);assert.equal(g.player.energy,100)});
test('buildings block movement and world limits contain players',()=>{const g=noEnemies(playing()),b=OBSTACLES[0];g.player.x=b.x;g.player.z=b.z+b.d/2+1;advance(g,2,{forward:1});assert.equal(circleHitsRect(g.player.x,g.player.z,MODES.foot.radius,b),false);g.player.x=0;g.player.z=-WORLD_LIMIT+1;advance(g,2,{forward:1});assert.ok(g.player.z>=-WORLD_LIMIT+MODES.foot.radius);assert.equal(g.boundary,true)});
test('15 Hz and 120 Hz frames preserve time and movement',()=>{const slow=noEnemies(playing()),fast=noEnemies(playing());advance(slow,8,{forward:1},15);advance(fast,8,{forward:1},120);assert.ok(Math.abs(slow.elapsed-fast.elapsed)<1e-9);assert.ok(Math.abs(slow.player.z-fast.player.z)<1e-7)});
test('bad deltas are ignored and stalls bounded',()=>{assert.throws(()=>createGame('jet'));const g=playing();stepGame(g,still,Infinity);stepGame(g,still,-1);assert.equal(g.elapsed,0);stepGame(g,still,5);assert.ok(Math.abs(g.elapsed-.25)<1e-9)});
test('practice still has a viable survival path',()=>{const g=playing('foot','easy');for(let i=0;i<46*120&&g.status==='playing';i++){g.player.yaw=-i/120*.7;stepGame(g,{forward:1},1/120)}assert.equal(g.status,'won');assert.ok(g.dodges>=4)});
